---
title: "table1.Rmd"
author: "Kristina Jordahl"
date: "5/5/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)

data(cars)
cars$outcome <- sample(c(0,1), replace = TRUE, size = 50)
```

### Make a function that creates Table 1

```{r table1fun}
Table1 <- function(data, variables, outcome) {
  final.table1 <- NULL
  for (v in variables) {
    if (class(data[, v]) == "factor") {
      count <- table(data[, v], data[, outcome], useNA="ifany")
      prop <- prop.table(table(data[, v], data[, outcome], useNA="ifany"), 2)
      table1 <- matrix(NA, nrow=(dim(count)[1]+1), ncol=(dim(count)[2]+1))
      
      colnames(table1) <- c("", colnames(count))
      rownames(count)[is.na(rownames(count))] <- "Missing"
      table1[, 1] <- c(paste0(v, " (N, %)"), paste0("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", rownames(count)))
      table1[1, 2:(dim(count)[2]+1)] <- rep("", dim(count)[2])
      
      for (i in 1:dim(count)[1]) {
        for (ii in 1:dim(count)[2]) {
          table1[i+1, ii+1] <- paste0(count[i, ii], " (", round(prop[i, ii], 2) * 100, "%)")
        }
      }
    }
    if (class(data[, v]) %in% c("integer", "numeric")) {
      temp1 <- aggregate(data[, v], list(data[, outcome]), mean)
      temp2 <- aggregate(data[, v], list(data[, outcome]), sd)
      table1 <- matrix(NA, nrow=1, ncol=(length(temp1$Group.1)+1))
      table1[1, 1] <- paste0(v, " (mean, SD)")
      colnames(table1) <- c("", as.character(temp1$Group.1))
      table1[1, 2:(length(temp1$Group.1)+1)] <- paste0(round(temp1$x, 2), " (", round(temp2$x, 2), ")")
    }
    final.table1 <- rbind(final.table1, table1)
  }
  table1 <<- final.table1
}
```

### Execute Table1 function

Name and label the values for each of the variables included in Table 1. Then, create Table 1 using the Table1 function.

```{r createtable1}
cars$Speed <- cars$speed
cars$Distance <- cars$dist
cars$outcome <- factor(cars$outcome, labels = c("Controls", "Cases"))
cars$outcome <- relevel(cars$outcome, ref = "Cases")

Table1(cars, c("Speed", "Distance"), "outcome")
kable(table1)
```